services:
  addon:
    build:
      context: .
      dockerfile: Dockerfile
    image: stremio-iptv-addon:latest
    container_name: iptv
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-public
      - vpn_network
      - cache_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-addon.rule=Host(`iptv-sandbox.duckdns.org`)"
      - "traefik.http.routers.iptv-addon.entrypoints=websecure"
      - "traefik.http.routers.iptv-addon.tls.certresolver=letsencrypt"
      - "traefik.http.services.iptv-addon.loadbalancer.server.port=7000"

networks:
  traefik-public:
    external: true
  vpn_network:
    external: true
  cache_network:
    external: true